version: '3.9'

services:
  database:
    container_name: nr-db
    image: mysql:8.0.28
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./LocalData/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: notreddit
      MYSQL_USER: notreddit
      MYSQL_PASSWORD: notreddit1234
      MYSQL_ROOT_PASSWORD: notreddit1234
  
  nginx:
    container_name: nr-nginx
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./LocalData/nginx:/var/log/nginx
      - ./server:/var/www/server

  php:
    container_name: nr-php-fpm
    image: php:8.1.3-fpm-bullseye
    ports:
      - 9000:9000
    volumes:
      - ./server:/var/www/server